[package]
name = "wikitools"
version = "0.0.0"
authors = ["cthwaite"]
edition = "2018"


[workspace]
members = [
    "storage",
]

[dependencies]
bzip2 = "0.3.1"
config = "0.9"
fnv =  "1.0"
lazy_static = "1.1"
pbr = "1.0"
qp-trie = "0.7.3"
quick-xml = "0.13"
rayon = "1.0"
regex = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
spinners = "1.0"
tantivy = "0.7"
zip = "0.4.2"
