[package]
name = "wikitools"
version = "0.0.0"
authors = ["cthwaite"]

[dependencies]
bzip2 = "0.3.1"
config = "0.9"
lazy_static = "1.1"
pbr = "1.0"
quick-xml = "0.13"
rayon = "1.0"
regex = "1.0"
serde = "1.0"
serde_derive = "1.0"
spinners = "1.0"
zip = "0.4.2"
