[package]
name = "core"
version = "0.1.0"
authors = ["cthwaite <cthwaite@gmail.co.uk>"]
edition = "2018"

[dependencies]
bzip2 = "0.3.1"
fnv = "1.0"
log = "^0.4"
pbr = "1.0"
spinners = "1.0"
config = "0.9"
serde = { version = "1.0", features = ["derive"] }