[package]
name = "tagme"
version = "0.1.0"
authors = ["cthwaite <cthwaite@gmail.co.uk>"]
edition = "2018"

[dependencies]
env_logger = "^0.6"
lazy_static = "1.1"
log = "^0.4"
regex = "1.0"
tantivy = "^0.9"
storage = { path = "../storage" }