[package]
name = "storage"
version = "0.1.0"
authors = ["cthwaite <cthwaite@gmail.co.uk>"]
edition = "2018"

[dependencies]
bincode = "^1.1"
rocksdb = "^0.12.0"
serde = { version = "1.0", features = ["derive"] }
tempfile = "^3.0"